### ISSUE TITLE
Conflict with Monk little details (condition name dissapear)

### ISSUE THREAD

**Issue by Fridan99** [mclemente/fvtt-condition-lab-triggler#14]
**Describe the bug**
the names in the conditions are not visible

**To Reproduce**
1. Install Monk Little details, Conditionlab & Trigglers, dnd5e system, and Foundry v11.307
2. Click on 'the status effect on any token in the canvas'
3. See error: you can't see the name of the status condition "Blinded, charmed, ......."

**Expected behavior**
See the conditions name.

**Screenshots**
![1 11](https://github.com/mclemente/fvtt-condition-lab-triggler/assets/86131373/ce62f020-b574-4f19-b11d-5c626b016282)

**Environment Info (please complete the following information):**

Dnd5e system 2.3.0

Foundry v11.307

Monk little details 11.04

Contitionlab & Trigglers 1.4.1

**Additional context**
There is an open issue on Monk Little Details.... 

https://github.com/ironmonk88/monks-little-details/issues/273

**Comment by IggydB** [comment]
I played around with enabling and disabling some items and found that this appears to be due to the setting in Condition Lab that removes the Default conditions from the Hud.

![image](https://github.com/ironmonk88/monks-little-details/assets/143030784/1687c721-9dd7-45ab-901e-b5147119143b)

It isn't all good news though, since disabling this setting adds those back in but doesn't remove the ones added by Condition lab, therefore Little Details is unable to add the naming to status effects it doesn't touch/own. 

![image](https://github.com/ironmonk88/monks-little-details/assets/143030784/a6257c50-6d3a-4660-bb1d-2a59f88b040c)


Would like to see some collaboration for integration between these two in the future as for the life of me I cannot get DFreds Convenient effects to properly do a stacking buff, therefore Condition lab is the only option I have and I'd like to see those names.

**Comment by KJTailor** [comment]
Here to +1 the issue, if possible, please. Both are great modules and I wouldn't want to miss one or the other.

**Comment by MythicalRollers** [comment]
I was able to reproduce this issue and resolve it with one caveat that I have yet to see anyone else mention.  For me. Dfred Convenient Effects was also adding to the list.  I have this only because d&dbeyond importer wants it, I do not actively use it. I set it to None under status effects in the settings for it, and my list is visible again. So for me the issue was related to Monk's, Dfreds, and Condition Lab & Triggler.

**Comment by KJTailor** [comment]
I wrote kind of a collation of the issue to DFred hoping they maybe can do something about it.

**Comment by mclemente** [comment]
Does this issue persists on MLD v6.0? Just tried to fix this issue and it is working fine right now.

**Comment by KJTailor** [comment]
I finally got around to check and found, indeed it is not persisting anymore!

**Comment by Fridan99** [comment]
It seems to be solved. Thank you, I close the thread
