### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by MotoMoto1234** [mclemente/fvtt-condition-lab-triggler#2]
1.  Could you by chance add a quick access button, old CUB had the button in settings sidebar, dfreds has it as a scene tool.  
2.  Can you add DAE integration in the active effect edit window inside the condition lab so that we can get the auto complete feature of dae?

**Comment by mclemente** [comment]
>Could you by chance add a quick access button, old CUB had the button in settings sidebar, dfreds has it as a scene tool.

I meant to add two keybinds. With all the changes I've done, I forgot to add that one.
I could add a setting to add them to the scene tools. Overall I dislike adding to scene tools because just 1 or 2 modules end up cluttering the bar already.

>Can you add DAE integration in the active effect edit window inside the condition lab so that we can get the auto complete feature of dae?

Did CUB had this or is this a new thing? If it had, it's from DAE and it needs to update to consider CLT as it did CUB.

**Comment by MotoMoto1234** [comment]
I showed the module to the author of DAE and Midi and he said he'd take a look when he has spare time.

**Comment by mclemente** [comment]
I've added both options to the latest release, check them out.
